#!/usr/bin/env node
const adapter = require('./universal-adapter');

async function go(host, username, password, macro) {
  const videoDevice = { host, username, password };
  await adapter(videoDevice);
  require(macro); // macro starts with xapi available
}

if (process.argv.length < 6) {
  console.log('Run a Webex Device macro remotely from a node.js environment');
  console.log('Usage: ./run-macro <host> <username> <password> <macrofile>');
  console.log('\neg: ./run 10.47.31.28 admin mypwd ./mymacro.js')
  process.exit(1);
}

const [exec, script, host, username, password, macro] = process.argv;
go(host, username, password, macro);
